### PR TITLE
[Screencap][AI/HS2] Fix "Images overlap when Press F11 quickly"

### LINKED ISSUE #212: Images overlap when Press F11 quickly
This problem first occurred when using video export. I found that the exported transparent background frames had overlapping images. After investigation, I found that the problem also occurred when pressing F11 quickly.

It seems that all previous frames are saved and overwritten by the current frame.

I recently moved the entire folder of HS2 from a mechanical hard drive to an SSD, and I'm not sure if this is the cause.

Samlpe:
HS2_2024-12-21-23-27-23-348
HS2_2024-12-21-23-27-23-524
HS2_2024-12-21-23-27-23-609
HS2_2024-12-21-23-27-23-666

### PR DESCRIPTION
**Pull request by altonjung**
- Fixed #212 
- changed screen capture actions in Update() to asynchronous way
  reason why: If video capture is performed in synchronous mode, the program occasionally freezes. Therefore, this process needs to be converted to a message-based asynchronous mode

### CODE REVIEW

File: src/AIHS2_Core_Screencap/ScreenshotManager.cs [hunk 1]
```diff
@@ -460,6 +482,9 @@ private RenderTexture CaptureTransparent(int width, int height, int downscaling)
 
             var alpha = RenderTexture.GetTemporary(scaledWidth, scaledHeight, 0, RenderTextureFormat.ARGB32, RenderTextureReadWrite.Default);
 
+            // initialize alpha background color
+            Graphics.Blit(Texture2D.blackTexture, alpha);
```
Comment (ManlyMarco) [inline src/AIHS2_Core_Screencap/ScreenshotManager.cs:486]: Isn't this change enough to fix the alpha overlap?

**Review by ManlyMarco — COMMENTED** [review]
This solution feels a bit weird. Can you confirm that this resolves the issue with VideoExport and not only with quickly pressing capture hotkeys?
